
version: '3.7'
name: money_map

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  streamlit:
    build:
        context: .
        dockerfile: .docker/Dockerfile.streamlit
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
